package de.schafunschaf.voidtec.ids;

public class VT_Strings {

    public static final String VT_DAMAGED_AUGMENT_DESC = "This Augment got damaged during battle. It can still be installed and will work at reduced efficiency.";
    public static final String VT_DESTROYED_AUGMENT_DESC = "This Augment is damaged beyond repair. It can't be installed and is nothing more than a heap of scrap in its current state.";

    public static final String VT_SHEEP_WIKI = "Domestic sheep (Ovis aries) are quadrupedal, ruminant mammals typically kept as livestock" + ". Although the name sheep applies to many species in the genus Ovis, in everyday usage it almost always refers to Ovis aries. Like all ruminants, sheep are members of the order Artiodactyla, the even-toed ungulates. Numbering a little over one billion, domestic sheep are also the most numerous species of sheep. An adult female is referred to as a ewe (/juː/), an intact male as a ram, occasionally a tup, a castrated male as a wether, and a young sheep as a lamb.\n" + "\n" + "Sheep are most likely descended from the wild mouflon of Europe and Asia, with Iran being a geographic envelope of the domestication center.[1] One of the earliest animals to be domesticated for agricultural purposes, sheep are raised for fleeces, meat (lamb, hogget or mutton) and milk. A sheep's wool is the most widely used animal fiber, and is usually harvested by shearing. Ovine meat is called lamb when from younger animals and mutton when from older ones in Commonwealth countries, and lamb in the United States (including from adults). Sheep continue to be important for wool and meat today, and are also occasionally raised for pelts, as dairy animals, or as model organisms for science.\n" + "\n" + "Sheep husbandry is practised throughout the majority of the inhabited world, and has been fundamental to many civilizations. In the modern era, Australia, New Zealand, the southern and central South American nations, and the British Isles are most closely associated with sheep production.\n" + "\n" + "There is a large lexicon of unique terms for sheep husbandry which vary considerably by region and dialect. Use of the word sheep began in Middle English as a derivation of the Old English word scēap; it is both the singular and plural name for the animal. A group of sheep is called a flock. Many other specific terms for the various life stages of sheep exist, generally related to lambing, shearing, and age.\n" + "\n" + "Being a key animal in the history of farming, sheep have a deeply entrenched place in human culture, and find representation in much modern language and symbology. As livestock, sheep are most often associated with pastoral, Arcadian imagery. Sheep figure in many mythologies—such as the Golden Fleece—and major religions, especially the Abrahamic traditions. In both ancient and modern religious ritual, sheep are used as sacrificial animals.";
}
